
version: "3"

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    restart: always
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
    external: true