services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - '127.0.0.1:5432:5432'
    restart: always
    environment:
      - POSTGRES_PASSWORD=internalpassword
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  bot:
    image: "ghcr.io/teamevie/evie:latest"
    env_file:
      - ".env"
    environment:
      - DATABASE_URL=postgresql://postgres:internalpassword@postgres:5432/bot?schema=public
    restart: "always"
    links:
      - postgres
volumes:
  postgres:
    external: true
