services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - '127.0.0.1:5432:5432'
    restart: always
    environment:
      - POSTGRES_PASSWORD=internalpassword
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres:
    external: true
