services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  bot:
    build: "./apps/bot"
    env_file:
      - "./apps/bot/.env"
    environment:
      - MONGO_URL=mongodb://root:password@mongodb:27017/bot?authSource=admin&retryWrites=true&w=majority
    restart: "always"
    links:
      - mongodb
volumes:
  mongo: