
version: "3"

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    restart: always
    networks:
      - app_network
    env_file:
      - ./apps/bot/.env
  tail:
    container_name: tail
    build:
      context: .
      dockerfile: ./apps/tail/Dockerfile
    restart: always
    networks:
      - app_network
    env_file:
      - ./apps/tail/.env
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
  redis:
    container_name: evie-redis
    image: redis:alpine
    restart: always
    networks:
      - app_network
    command: redis-server

networks:
  app_network:
    external: true