name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/cd.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  PublishEvie:
    name: Publish Evie image to container registries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          submodules: true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1.6.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Evie Docker image
        uses: docker/build-push-action@309fb9180f2030167151ad947584dc32f6164656
        with:
          push: true
          context: ./
          tags: |
            ghcr.io/twisttaan/evie:latest
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
         SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
         SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
         SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
         environment: production
