name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  BuildBot:
    name: Building Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build code
        run: cd apps/bot && yarn build
  BuildFrontend:
    name: Building Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build code
        run: cd apps/frontend && yarn build
