name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  BuildBot:
    name: Build Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
        working-directory: ./services/bot
      - name: Compile TypeScript
        run: yarn build
        working-directory: ./services/bot

  BuildApi:
    name: Build Api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
        working-directory: ./services/api
      - name: Compile TypeScript
        run: yarn build
        working-directory: ./services/api
