name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  BuildBackend:
    name: Building Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
        working-directory: ./services/backend
      - name: Build code
        run: yarn build
        working-directory: ./services/backend
