name: Publish Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: .
            file: ./apps/bot/Dockerfile
            tag: ghcr.io/teamevie/evie
          - context: .
            file: ./apps/tail/Dockerfile
            tag: ghcr.io/teamevie/tail
          - context: .
            file: ./apps/tag/Dockerfile
            tag: ghcr.io/teamevie/tag
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: teamevie
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: ${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
