name: Sentry

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/sentry.yml"
      - "package.json"
      - "yarn.lock"

jobs:
  UploadSentry:
    name: Upload Sentry release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build code
        run: yarn build
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: "./dist"
          version: ${{ steps.package-version.outputs.current-version}}
